config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  # devise_scope :user do
  #   post "change_validation", to: "registrations#change_validation"
  # end

  resources :organizations, except: [:destroy] do
    devise_scope :user do
      get "new_user_organization", to: "registrations#new_user_organization"
      post "create_new_user_organization", to: "registrations#create_new_user_organization"
    end
  end
  resources :events, except: :destroy do
    resources :orders, except: [:edit, :update, :destroy]
  end
  resource :event_categories, except: [:index, :show]
  resources :tickets, except: [:edit, :update, :destroy]
  resources :venues, only: [:index, :show]
  resources :clients, except: [:destroy, :new, :create]

  get "validation", to: "tickets#validation"
  post "change_validation", to: "pages#change_validation"
  get "print_all/:id", to: "orders#print_all", as: :print_all
  # get "clients/new/:order_id", to: "clients#new", as: :new_client
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event_category.rb
class EventCategory < ApplicationRecord
  belongs_to :event
  has_many :tickets, dependent: :destroy

  validates_presence_of :price, :capacity, :name
  validates :price, numericality: true

  def percentage_sold
    (tickets.count.to_f / capacity * 100).round
  end
end

app/controllers/event_categories_controller.rb
class EventCategoriesController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
    @event_category = EventCategory.find(params[:format].to_i)
    @event = @event_category.event

    authorize @event_category

    @event_category.destroy
    redirect_to edit_event_path(@event.id)
  end
end

app/views/event_categories/_fields.html.erb
<%= content_tag :div, class: "nested-fields", data: { new_record: form.object.new_record? } do %>

  <div class="form-row" >

    <div class="form-group col">
      <%= form.input :name, class: "form-control" %>
    </div>

    <div class="form-group col">
      <%= form.input :price, class: "form-control" %>
    </div>

    <div class="form-group col">
      <%= form.input :capacity, class: "form-control" %>
    </div>

    <div class="form-group col d-flex justify-content-around align-items-center">

      <% if form.object.id.nil? %>

        <%= link_to '',
          data: {
            action: 'click->event_category_add#removeField'
            } do %>
            <i class="fas fa-trash-alt"></i>
        <% end %>

      <% else %>

        <%= link_to event_categories_path(form.object.id),
          method: :delete,
          data: {
            confirm: "Are you sure?",
            action: 'click->event_category_add#removeField'
            } do %>
            <i class="fas fa-trash-alt"></i>
        <% end %>

      <% end %>

    </div>

    <%= form.hidden_field :_destroy %>

  </div>

<% end %>

app/views/event_categories/edit.html.erb
<h1>EventCategories#edit</h1>
<p>Find me in app/views/event_categories/edit.html.erb</p>

app/views/event_categories/new.html.erb
<h1>EventCategories#new</h1>
<p>Find me in app/views/event_categories/new.html.erb</p>