config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  # devise_scope :user do
  #   post "change_validation", to: "registrations#change_validation"
  # end

  resources :organizations, except: [:destroy] do
    devise_scope :user do
      get "new_user_organization", to: "registrations#new_user_organization"
      post "create_new_user_organization", to: "registrations#create_new_user_organization"
    end
  end
  resources :events, except: :destroy do
    resources :orders, except: [:edit, :update, :destroy]
  end
  resource :event_categories, except: [:index, :show]
  resources :tickets, except: [:edit, :update, :destroy]
  resources :venues, only: [:index, :show]
  resources :clients, except: [:destroy, :new, :create]

  get "validation", to: "tickets#validation"
  post "change_validation", to: "pages#change_validation"
  get "print_all/:id", to: "orders#print_all", as: :print_all
  # get "clients/new/:order_id", to: "clients#new", as: :new_client
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<div class="banner"
  style="background-image:
    linear-gradient(120deg, rgba(0,0,0,0.1), rgba(0,0,0,.3)),
    url('https://picsum.photos/id/1058/2000/1500.jpg')">
  <div class="container">
    <div class="banner-content">
      <div class="banner-content-text">
        <h1>Your tix, our fix 🎉</h1>
        <br>
        <h2>Digitalize ticketing for your: <span id="banner-typed-text"></span></h2>
      </div>
      <%= link_to 'Create your first event', new_event_path, class: 'btn-1' %>
    </div>
  </div>
  <div class="arrow-down">
    <a href="#what-we-do"><i class="text-light fas fa-chevron-down fa-2x"></i></a>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Made with ❤ at TixFix 🎟
  </div>
</div>

app/views/shared/_modal.html.erb
<%# -------------------------------------------------------------------------------------- %>
<%# Bootstrap Modal %>

<div class="modal fade" id=<%= modal_name %> tabindex="-1" role="dialog" aria-labelledby=<%= "#{modal_name}Label" %> aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">

      <div class="modal-header">

        <h2 class="modal-title" id=<%= "#{modal_name}Label" %>>[Modal Title]</h2>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>

      </div>

      <div class="modal-body">

        [Modal content]

      </div>
        <div class="modal-footer">
          <%= link_to 'Close', 'url_suffix_path', class: 'btn-2', data: { dismiss: 'modal' } %>

          <%= link_to 'Send', 'url_suffix_path', class: 'btn-1' %>
        </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<%# https://github.com/lewagon/awesome-navbars/blob/master/templates/_navbar_wagon_without_login.html.erb %>
<div class="navbar navbar-expand-sm navbar-lewagon px-3 mb-4 <%= controller_name == 'pages' ? 'fixed-top' : 'navbar-lewagon-white sticky-top' %>">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo.png", alt: '', class: '' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav me-auto">

    <%# Nota-bene --removed 'nav-item' bootstrap class to override a tags styling %>

      <% if user_signed_in? %>

        <li class="nav-item">
          <div class="custom-control custom-switch">
            <%= link_to change_validation_path, method: :post do %>
              <input type="checkbox" <%= 'checked' if current_user.is_validation %> class="custom-control-input" id="customSwitches">
              <label class="custom-control-label pointer <%= 'nav-item-dark' unless controller_name == "pages" && action_name == "home" %>" for="customSwitches">Validation Mode</label>
            <% end %>
          </div>
        </li>

        <li class="nav-item active">
          <%= link_to "Events", events_path, class: "nav-link" %>
        </li>

      <% end %>

      <li class="nav-item">
        <%= link_to 'Create event', new_event_path, class: 'btn btn-1' %>
      </li>

      <% if user_signed_in? %>

        <li class="nav-item dropdown">
          <%#= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, alt: "avatar" %>
          <% else %>
            <div class="avatar dropdown-toggle" style="background: white" id="navbarDropdown" data-toggle="dropdown" data-aria-haspopup="true" data-aria-expanded="false" alt="avatar">
              <%= current_user.name.first%>
            </div>
          <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <p class="dropdown-item">Hi <%= current_user.name %></p>
            <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Organization", organization_path(current_user.organization), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% else %>

        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>

      <% end %>

    </ul>
  </div>
</div>

app/views/shared/_ticket_pdf.html.erb
<div class="pdf-body">

  <div class="d-flex justify-content-between align-items-center mb-3">

    <div class="mr-3">
      <%= image_tag "logo.png", alt: '', class: 'pdf-logo' %>
      <br>
      <h1 class="mt-3 js-title">
        <%= event.name %>
      </h1>
    </div>

    <span class='pdf-qr'><%= ticket.qr_code(7) %></span>
  </div>

  <div class="d-flex justify-content-between align-items-center mb-5">
    <div>
      <h2>
        <%= event.starts_at.strftime("%A, #{event.starts_at.day.ordinalize} %b %Y, %-l:%M%p") %>
      </h2>
      <p>Order#: <%= order.id %></p>
      <p>Tix#: <%= ticket.hex %></p>

      <p class="mb-3">
        Issued: <%= ticket.created_at.strftime("%A, #{ticket.created_at.day.ordinalize} %b %Y, %-l:%M%p") %>
      </p>
    </div>

    <div class="pdf-text-right">
      <h1>
        <%= event_category.name %>
      </h1>

      <h1>
        €<%= event_category.price %>
      </h1>
    </div>
  </div>

  <div class="pdf-flyer d-flex justify-content-around align-items-center pdf-bg-darker">
    <% if event.image.attached? %>
      <%= cl_image_tag event.image.key, crop: :fill, alt: "event flyer", class: "pdf-flyer-img" %>
    <% else %>
      <h1>FUN!</h1>
    <% end %>
  </div>

  <br>

  <div class="d-flex justify-content-end">

    <%= link_to 'Print tix', '', class: 'btn-1', onclick: 'window.print()' %>

  </div>
</div>