config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  # devise_scope :user do
  #   post "change_validation", to: "registrations#change_validation"
  # end

  resources :organizations, except: [:destroy] do
    devise_scope :user do
      get "new_user_organization", to: "registrations#new_user_organization"
      post "create_new_user_organization", to: "registrations#create_new_user_organization"
    end
  end
  resources :events, except: :destroy do
    resources :orders, except: [:edit, :update, :destroy]
  end
  resource :event_categories, except: [:index, :show]
  resources :tickets, except: [:edit, :update, :destroy]
  resources :venues, only: [:index, :show]
  resources :clients, except: [:destroy, :new, :create]

  get "validation", to: "tickets#validation"
  post "change_validation", to: "pages#change_validation"
  get "print_all/:id", to: "orders#print_all", as: :print_all
  # get "clients/new/:order_id", to: "clients#new", as: :new_client
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :client, optional: true
  belongs_to :event
  has_many :tickets, dependent: :destroy

  accepts_nested_attributes_for :tickets, allow_destroy: true

  after_create :create_client

  def inventory
    # returns a hash of {event_category (obj) => tickets (obj) }
    hash = {}
    tickets.group_by(&:event_category).each do |key, value|
      hash[key.id] = value.count
    end
    hash
    # Ticket.where(order_id: self.id).group(:event_category_id).count
  end

  def create_client
    Client.create!(order: self)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_event, only: [:new, :create, :index, :show]

  def index
    @orders = policy_scope(Order)
  end

  def show
    @order = Order.find(params[:id])
    authorize @order
  end

  def new
    @order = Order.new
    authorize @order
  end

  def create
    @order = Order.create!(event: @event)
    authorize @order
    @event.event_categories.each do |category|

      if params[:tickets_for].first.keys.include?(category.id.to_s)

        n_tickets = params[:tickets_for].first[category.id.to_s].to_i

        n_tickets.times do
          Ticket.create!(
            order: @order,
            event_category: category,
            is_used: false,
            )
          end
        end
      end

    client = Client.create
    @order.client = client

    if @order.save!
      redirect_to event_order_path(@event.id, @order.id), notice: 'Order successfully created.'
    else
      flash.now[:alert] = "Error: #{@order.errors.full_messages.join("\n")}"
      render :new
    end
  end

  def print_all
    @order = Order.find(params[:id])
    authorize @order
    render 'orders/print_all', layout: 'pdf'
  end

  private

  def orders_params
    params.require(:order).permit(:event_id, :client_id, :tickets_for)
  end

  def set_event
    @event = Event.find(params[:event_id])#.includes(:order)
  end
end

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-lg-10 offset-lg-1 bg-white rounded-lg p-3 mt-3 mb-5">
      <div class="table-responsive">

        <div class="d-flex justify-content-between align-items-end">
          <div class="mt-3 bg-white">
            <%= link_to event_path(@event.id), method: :get, class: '' do %>
              <h1 class="text-shadow-light"><%= @event.name %></h1>
            <% end%>
            <h3><%= @event.starts_at.strftime("%a %d %b %Y, %-l:%M%p") %></h3>
            <h3>Orders</h3>
          </div>

          <%= link_to '+ New Order', new_event_order_path(@event.id), method: :get, class: 'btn-1 float-right', style: 'min-width: 120px' %>
        </div>

        <table class="table table-striped table-hover mt-3 mb-3">

              <thead class="thead-light">
                <tr>
                  <th scope="col">#id</th>
                  <th scope="col">Date</th>
                  <% @event.event_categories.each do |category| %>
                    <th scope="col">
                      <%= category.name %>
                      (€<%= category.price %>/p)
                    </th>
                  <% end %>
                  <th>Order total</th>
                </tr>
                <tr>
                  <th>Sum</th>
                  <th><%=  Time.now.strftime("%d %b, %-l:%M%p")%></th>
                    <% @event.event_categories.each do |category| %>
                      <th><%= category.tickets.count %></th>
                    <% end %>
                  <th>€<%= total_revenue(@event) %></th>
                </tr>
              </thead>
          <tbody>
            <% @event.orders.each do |order| %>
              <%# Makes row clickable %>
              <%# See: https://stackoverflow.com/questions/17147821/how-to-make-a-whole-row-in-a-table-clickable-as-a-link %>
              <tr onclick="window.location='<%= event_order_path(@event.id, order.id) %>';" style="cursor: pointer">
                <th scope="row">
                    <%= order.id %>
                </th>
                <th>
                  <%= order.created_at.strftime("%d %b, %-l:%M%p")%>
                </th>
                <% @event.event_categories.each do |category| %>
                  <th>
                    <% if order.inventory[category.id].nil? %>
                      --
                    <% else %>
                      <%= order.inventory[category.id] %>
                    <% end %>
                  </th>
                <% end %>
                <th>
                  €<%= order.tickets.map { |ticket| ticket.event_category.price }.sum %>
                </th>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="d-flex justify-content-end">
        <%= link_to 'Back to Event', event_path(@event.id), method: :get, class: 'btn-1 mr-3' %>

        <%= link_to '', method: :get, class: 'btn-2 mr-3' do %>
          Back to Top
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/orders/new.html.erb
<%= render '../views/shared/forms/form_top'%>

  <h1>New Order</h1>
  <br>
  <%= simple_form_for [ @event, @order ] do |f| %>
    <% @event.event_categories.each do |category| %>
      <div class="row d-flex justify-content-between align-items-center">
        <div class="form-group col">
          <h2 class="m-0 text-shadow-light"><%= category.name %></h2>
          <p>(<%= category.price %>€)</p>
        </div>

        <div class="form-group col d-flex justify-content-end">
          <%= number_field_tag "tickets_for[]#{category.id}"%>
        </div>
      </div>
    <% end %>
    <%= f.submit :submit, class: "btn-1", value: "Create Order" %>
  <% end %>
  <div class="d-flex">
    <%= link_to 'Back to Event', event_path(@event.id), method: :get, class: 'btn-2 mr-3' %>
    <%= link_to 'Back to Orders', event_orders_path(@event.id), method: :get, class: 'btn-2 mr-3' %>
  </div>

<%= render '../views/shared/forms/form_bottom'%>

app/views/orders/print_all.html.erb
<% @order.tickets.each do |ticket| %>

  <%= render 'shared/ticket_pdf',
    ticket: ticket,
    event_category: ticket.event_category,
    event: @order.event,
    order: @order
  %>

<% end %>
<br>

app/views/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-lg-8 offset-lg-2 bg-white rounded-lg p-3 mt-3 mb-5">

      <%= link_to event_path(@event.id), method: :get, class: '' do %>
        <h1 class="text-shadow-light"><%= @event.name %></h1>
      <% end%>

      <p class="text-muted">Order #<%= @order.id %></p>

      <div class="container-tickets">
        <% @order.tickets.each do |ticket| %>
          <div class="d-flex justify-space-between align-items-center">
            <div class="card-ticket-stripe flex-grow-1">
              <div class="card-ticket-stripe-left">
                <div class="card-ticket-img">
                  <% if @event.image.attached? %>
                    <%= cl_image_tag @event.image.key, crop: :fill, alt: "event flyer" %>
                  <% else %>
                    <%= image_tag 'placeholder.jpg' %>
                  <% end %>
                </div>

                <div class="card-ticket-stripe-info-left">
                  <h1 class="truncate"><%= @event.name %></h1>
                  <p class="truncate text-muted"><%= @event.starts_at.strftime("%a %d %b %Y, %-l:%M%p") %></p>
                  <small class="truncate text-monospace text-primary"><%= ticket.hex %></small>
                </div>
              </div>

              <div class="card-ticket-stripe-right">
                <div class="card-ticket-stripe-info-right">
                  <p class="text-muted"><%= ticket.event_category.name %></p>
                  <h1>€<%= ticket.event_category.price %></h1>

                  <% if ticket.is_used %>
                    <small class="danger">
                      Used ❌
                    </small>
                  <% else %>
                    <small>
                      Valid ✔
                    </small>
                  <% end %>
                </div>

                <div class="card-ticket-qr">
                  <%= ticket.qr_code(2) %>
                </div>
              </div>
            </div>

            <div class="mb-3 d-flex">
              <%= link_to '',
                #  DO NOT SPECIFY method: GET here ! you'll have the modal disappear
                class: 'icon-btn',
                data: { toggle: "modal",
                        target: "#sendTicketModal",
                        ticket_id: ticket.id,
                        order_id: ticket.order.id,
                        client_id: ticket.order.client.id,
                         } do %>
                <i class="far fa-paper-plane"></i>
              <% end %>

              <%= link_to ticket_path(ticket.id), method: :get, class: 'icon-btn', target: '_blank' do %>
                <i class="fas fa-print"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>

      <div class="d-flex justify-content-end">
        <%= link_to event_path(@event.id), method: :get, class: 'btn-2 mr-3 m-2' do %>
          Back to Event
        <% end %>

        <%= link_to event_orders_path(@event.id), method: :get, class: 'btn-2 mr-3 m-2' do %>
          Back to Orders
        <% end %>

        <%= link_to print_all_path(@order.id), method: :get, target: "_blank", class: 'btn-1 mr-3 m-2' do %>
          Print all <i class="fas fa-print"></i>
        <% end %>

        <%= link_to '',
          #  DO NOT SPECIFY method: GET here ! you'll have the modal disappear
          class: 'btn-1 mr-3 m-2',
          data: { toggle: "modal",
                  target: "#sendTicketModal",
                  order_id: @order.id,
                  client_id: @order.client.id,
                } do %>
          Send all <i class="far fa-paper-plane"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%# Link to modal partial %>
<%= render 'shared/modal', modal_name: "sendTicketModal" %>