config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  # devise_scope :user do
  #   post "change_validation", to: "registrations#change_validation"
  # end

  resources :organizations, except: [:destroy] do
    devise_scope :user do
      get "new_user_organization", to: "registrations#new_user_organization"
      post "create_new_user_organization", to: "registrations#create_new_user_organization"
    end
  end
  resources :events, except: :destroy do
    resources :orders, except: [:edit, :update, :destroy]
  end
  resource :event_categories, except: [:index, :show]
  resources :tickets, except: [:edit, :update, :destroy]
  resources :venues, only: [:index, :show]
  resources :clients, except: [:destroy, :new, :create]

  get "validation", to: "tickets#validation"
  post "change_validation", to: "pages#change_validation"
  get "print_all/:id", to: "orders#print_all", as: :print_all
  # get "clients/new/:order_id", to: "clients#new", as: :new_client
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_one_attached :logo
  has_many :users, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :venues, through: :events
  has_many :orders, through: :events

  accepts_nested_attributes_for :users

  validates :name, presence: true, uniqueness: true
  validates :website, uniqueness: true, allow_nil: true
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: %i[show edit update]

  def new
  end

  def create
  end

  def edit
    set_organization
  end

  def update
    set_organization
    if @organization.update(organization_params)
      authorize @organization
      redirect_to @organization, notice: 'Organization was sucessfully updated'
    else
      render :edit
    end
  end

  def index
    @organizations = policy_scope(Organization)
  end

  def show
    set_organization
  end

  private

  def organization_params
    params.require(:organization).permit(:name, :website)
  end

  def set_organization
    @organization = Organization.find(params[:id])
    authorize @organization
  end
end

app/views/organizations/create.html.erb
<h1>Organizations#create</h1>
<p>Find me in app/views/organizations/create.html.erb</p>

app/views/organizations/edit.html.erb
<%= render '../views/shared/forms/form_top'%>

  <h2>Edit Organization
  <%= simple_form_for(@organization) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <%= f.input :name %>
    <%= f.input :website%>
    <%= f.button :submit, class: "btn-1"%>
  <% end %>

<%= render '../views/shared/forms/form_bottom'%>

app/views/organizations/index.html.erb
<h1>Organizations</h1>

<% @organizations.each do |organization| %>
  <p><%= link_to organization.name, organization %></p>
<% end %>

app/views/organizations/new.html.erb
<% if policy(Organization).create? %>
  <%= link_to "New organization", new_organization_path %>
<% end %>

app/views/organizations/show.html.erb
<div class="container justify-content-between bg-white rounded p-3">
  <h1><%= @organization.name %></h1>
    <p><%= @organization.website %></p>
  <%= link_to 'Edit organization', edit_organization_path %>
</div>

app/views/organizations/update.html.erb
<h1>Organizations#update</h1>
<p>Find me in app/views/organizations/update.html.erb</p>